### ISSUE TITLE
pycapnp chokes on c++ speicifc lines in pp.capnp that it should ignore.

### ISSUE THREAD

**Issue by glycerine** [capnproto/pycapnp#17]
pycapnp (37f0dc4 used with capnp 0.3 on linux amd64 / python 2.7) chokes on the c++ specific parts of a .capnp file on import.

Here is an example. The line starting with "using Cxx" and the line starting with "$Cxx" both cause pycapnp to choke.

pp.capnp:

```
@0xb8436490a97cb059;

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("ztix");

struct Zdate {
  year  @0   :Int16;
  month @1   :UInt8;
  day   @2   :UInt8;
}


```

here is a log of trying with either of the Cxx specific lines in:

```
>>> import capnp
>>> import pp_capnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "capnp.pyx", line 1404, in capnp.capnp._Loader.load_module (capnp/capnp.cpp:20783)
  File "capnp.pyx", line 1383, in capnp.capnp.load (capnp/capnp.cpp:20323)
  File "capnp.pyx", line 1073, in capnp.capnp.SchemaParser.load (capnp/capnp.cpp:18270)
  File "capnp.pyx", line 947, in capnp.capnp.SchemaParser._parse_disk_file (capnp/capnp.cpp:16193)
RuntimeError: /vagrant/cnet/thrift_to_capnp/pp.capnp:3: bug in code: Not defined: Cxx
stack: 0x7f1cc680059c 0x7f1cc701cab4 0x7f1cc701ceff 0x7f1cc7015f21 0x7f1cc701647f 0x7f1cc7002116 0x7f1cc7005335 \
0x7f1cc7005b8a 0x7f1cc701252e 0x7f1cc7013385 0x7f1cc70134de 0x7f1cc70137f5 0x7f1cc701b596 0x7f1cc701b63d 0x7f1cc\
7260b62 0x4f7496
>>> 
vagrant@vagrant-ubuntu:~/dev/cnet/thrift_to_capnp$ python
Python 2.7.3 (default, Sep 26 2013, 20:03:06)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import capnp
>>> import pp_capnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "capnp.pyx", line 1404, in capnp.capnp._Loader.load_module (capnp/capnp.cpp:20783)
  File "capnp.pyx", line 1383, in capnp.capnp.load (capnp/capnp.cpp:20323)
  File "capnp.pyx", line 1073, in capnp.capnp.SchemaParser.load (capnp/capnp.cpp:18270)
  File "capnp.pyx", line 947, in capnp.capnp.SchemaParser._parse_disk_file (capnp/capnp.cpp:16193)
RuntimeError: /vagrant/cnet/thrift_to_capnp/pp.capnp:2: bug in code: Import failed: /capnp/c++.capnp
stack: 0x7ff5196f259c 0x7ff519f0eab4 0x7ff519f0eeff 0x7ff519f08350 0x7ff519f084dd 0x7ff5196f8562 0x7ff519f019b1 \
0x7ff519f06d33 0x7ff519f06f3d 0x7ff519f07e14 0x7ff519f0847f 0x7ff519ef4116 0x7ff519ef7335 0x7ff519ef7b8a 0x7ff51\
9f0452e 0x7ff519f05385
>>> 
```

pycapnp should ignore lines that aren't meant for python.

**Comment by srujan-venkata** [comment]
To those who find them selfs here again if the sys.path.append doesn't work.  pass the c++.capnp path to the load like
capnp.load("<capnp_path>", imports=["/usr/local/include"])
