### ISSUE TITLE
 undefined symbol: _ZN2kj1_24TransformPromiseNodeBase7onReadyERNS0_5EventE

### ISSUE THREAD

**Issue by balbassam** [capnproto/pycapnp#193]
Using python 3.8 I've been getting the following error on import. 

```
python -c 'import capnp'                                                                        (env: test) 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gh0s1/.virtualenvs/test/lib/python3.8/site-packages/capnp/__init__.py", line 34, in <module>
    from .version import version as __version__
  File "/home/gh0s1/.virtualenvs/test/lib/python3.8/site-packages/capnp/version.py", line 4, in <module>
    from .lib.capnp import _CAPNP_VERSION_MAJOR as LIBCAPNP_VERSION_MAJOR
ImportError: /home/gh0s1/.virtualenvs/test/lib/python3.8/site-packages/capnp/lib/capnp.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2kj1_24TransformPromiseNodeBase7onReadyERNS0_5EventE
```

I tried installing capnproto from git, pycapnproto from git as well as the pip + distribution provided packages to no avail. 

I can confirm that the symbol exists in the referenced library 
```
readelf -Ws /home/gh0s1/.virtualenvs/test/lib/python3.8/site-packages/capnp/lib/capnp.cpython-38-x86_64-linux-gnu.so | grep TransformPromiseNodeBase7
   194: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN2kj1_24TransformPromiseNodeBase7onReadyERNS0_5EventE
  4816: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN2kj1_24TransformPromiseNodeBase7onReadyERNS0_5EventE```

**Comment by haata** [comment]
If I recall, issues like this are from a mixing of the system capnproto libraries and the pycapnp downloaded capnproto libraries (as they are set to different versions)

You can try to see if my forked version (many fixes and updates) works for you.
https://github.com/haata/pycapnp-async
(there are some Windows capnp server tests failing, but everything else seems to be working)

**Comment by balbassam** [comment]
Your fork worked amazingly!!! Your fixes should be pushed upstream IMO. Great work!

**Comment by CLgithub** [comment]
> If I recall, issues like this are from a mixing of the system capnproto libraries and the pycapnp downloaded capnproto libraries (as they are set to different versions)
> 
> You can try to see if my forked version (many fixes and updates) works for you.
> https://github.com/haata/pycapnp-async
> (there are some Windows capnp server tests failing, but everything else seems to be working)

When I import capon get the following error:
```
>>> import capnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/__init__.py", line 35, in <module>
    from .version import version as __version__
  File "/home/ubuntu/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/version.py", line 5, in <module>
    from .lib.capnp import _CAPNP_VERSION_MAJOR as LIBCAPNP_VERSION_MAJOR
ImportError: /home/ubuntu/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/lib/capnp.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2kj1_24TransformPromiseNodeBase7onReadyEPNS0_5EventE
```

Any idea how to fix it?
Thanks

**Comment by sohamm17** [comment]
I also get similar error for pycapnp 0.6.1-4 for python3.8 and get segmentation fault for `import capnp`:

```
  File "/home/soham/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/__init__.py", line 34, in <module>
    from .version import version as __version__
  File "/home/soham/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/version.py", line 4, in <module>
    from .lib.capnp import _CAPNP_VERSION_MAJOR as LIBCAPNP_VERSION_MAJOR
ImportError: /home/soham/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/lib/capnp.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2kj9TimerImpl6atTimeENS_8AbsoluteINS_8QuantityIlNS_1_15NanosecondLabelEEENS3_9TimeLabelEEE
>>> import capnp 
Segmentation fault (core dumped)
```
