### ISSUE TITLE
Fail to import on Python 3.8

### ISSUE THREAD

**Issue by AstraLuma** [capnproto/pycapnp#224]
```
🐚 python
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import capnp
>>> import shushdb.proto_capnp
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 908, in _find_spec
AttributeError: '_Importer' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 910, in _find_spec
  File "<frozen importlib._bootstrap>", line 884, in _find_spec_legacy
  File "capnp/lib/capnp.pyx", line 4024, in capnp.lib.capnp._Importer.find_module
TypeError: can only concatenate list (not "_NamespacePath") to list
```

[Source capnp](https://github.com/go-build-it/shushdb/blob/master/shushdb/proto.capnp)

**Comment by haata** [comment]
Hmm, is the proto.capnp file in a subdirectory?

**Comment by astronouth7303** [comment]
Yeah, calling from the root of the project linked (ie, following usual python module stuff).

**Comment by astronouth7303** [comment]
The funky bit might be the lack of `__init__.py` (which was required in Py2 but not in Py3).

**Comment by haata** [comment]
From your source file called proto.capnp the correct sequence would be

```
python
import capnp
import proto_capnp
```

```bash
(pycapnp) [master]: python                                                                          [~/git/pycapnp/tt]
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import capnp
>>> import proto_capnp
>>> exit()
(pycapnp) [master]: ls                                                                              [~/git/pycapnp/tt]
proto.capnp
```
I had to fix the ObjRef union to start from `@0` to get it to work.
