### ISSUE TITLE
Win32 multiple build failures with 0.6.4 from Pypi

### ISSUE THREAD

**Issue by kfsone** [capnproto/pycapnp#232]
System: Windows 10, Build 20175.1000, x86_64,
Python: 3.8.5,
Pip: 20.2.1,
Shell: Powershell core,
Visual Studio:
- Visual Studio 16 (2019) Preview,
- Visual Studio 16 (2019) Professional,
- Visual Studio 15 (2017) Professional,

I was aiming to install the binary, but it insists on trying to build from source. I don't have lipcapnp binaries installed on the system, and if I did, how would it know where to find them in the windows world?

A couple of callouts from the errors:

```
  cl : Command line warning D9002 : ignoring unknown option '--std=c++11'
```

but when I git clone the repos, you're specifying 14.

```
  C:\Users\oliver\AppData\Local\Temp\tmpihu31iv9\vers.cpp(4): fatal error C1083: Cannot open include file: 'capnp/common.h': No such file or directory
  *WARNING* no libcapnp detected or rebuild forced. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
  fetching https://capnproto.org/capnproto-c++-0.6.1.tar.gz into C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\bundled
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for pycapnp
```

Cython complains about the lack of a language_level directive and appears to fall back to Py2, which is going to mess up compiling against py3 eventually:

```
    [1/1] Cythonizing capnp/lib\capnp.pyx
    C:\Users\oliver\AppData\Roaming\Python\Python38\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\capnp\lib\capnp.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
```

Full output:
```
> pip install --prefer-binary --upgrade --force pycapnp
Collecting pycapnp
  Using cached pycapnp-0.6.4.tar.gz (531 kB)
Building wheels for collected packages: pycapnp
  Building wheel for pycapnp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\oliver\\AppData\\Local\\Temp\\pip-install-_0a_gt5x\\pycapnp_08ef60c046434841a72612502102f1f0\\setup.py'"'"'; __file__='"'"'C:\\Users\\oliver\\AppData\\Local\\Temp\\pip-install-_0a_gt5x\\pycapnp_08ef60c046434841a72612502102f1f0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\oliver\AppData\Local\Temp\pip-wheel-1ijckdmu'
       cwd: C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\capnp
  copying capnp\version.py -> build\lib.win-amd64-3.8\capnp
  copying capnp\_gen.py -> build\lib.win-amd64-3.8\capnp
  copying capnp\__init__.py -> build\lib.win-amd64-3.8\capnp
  copying capnp\__init__.pxd -> build\lib.win-amd64-3.8\capnp
  copying capnp\c++.capnp -> build\lib.win-amd64-3.8\capnp
  copying capnp\schema.capnp -> build\lib.win-amd64-3.8\capnp
  creating build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\helpers.pxd -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\non_circular.pxd -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\__init__.pxd -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\asyncHelper.h -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\capabilityHelper.h -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\checkCompiler.h -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\fixMaybe.h -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\rpcHelper.h -> build\lib.win-amd64-3.8\capnp\helpers
  copying capnp\helpers\serialize.h -> build\lib.win-amd64-3.8\capnp\helpers
  creating build\lib.win-amd64-3.8\capnp\includes
  copying capnp\includes\capnp_cpp.pxd -> build\lib.win-amd64-3.8\capnp\includes
  copying capnp\includes\schema_cpp.pxd -> build\lib.win-amd64-3.8\capnp\includes
  copying capnp\includes\types.pxd -> build\lib.win-amd64-3.8\capnp\includes
  copying capnp\includes\__init__.pxd -> build\lib.win-amd64-3.8\capnp\includes
  creating build\lib.win-amd64-3.8\capnp\lib
  copying capnp\lib\capnp.pxd -> build\lib.win-amd64-3.8\capnp\lib
  copying capnp\lib\__init__.pxd -> build\lib.win-amd64-3.8\capnp\lib
  copying capnp\lib\pickle_helper.py -> build\lib.win-amd64-3.8\capnp\lib
  copying capnp\lib\__init__.py -> build\lib.win-amd64-3.8\capnp\lib
  copying capnp\lib\capnp.pyx -> build\lib.win-amd64-3.8\capnp\lib
  creating build\lib.win-amd64-3.8\capnp\templates
  copying capnp\templates\module.pyx -> build\lib.win-amd64-3.8\capnp\templates
  copying capnp\templates\setup.py.tmpl -> build\lib.win-amd64-3.8\capnp\templates
  running build_ext
  creating Users
  creating Users\oliver
  creating Users\oliver\AppData
  creating Users\oliver\AppData\Local
  creating Users\oliver\AppData\Local\Temp
  creating Users\oliver\AppData\Local\Temp\tmpihu31iv9
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /TpC:\Users\oliver\AppData\Local\Temp\tmpihu31iv9\vers.cpp /FoUsers\oliver\AppData\Local\Temp\tmpihu31iv9\vers.obj --std=c++11
  cl : Command line warning D9002 : ignoring unknown option '--std=c++11'
  vers.cpp
  C:\Users\oliver\AppData\Local\Temp\tmpihu31iv9\vers.cpp(4): fatal error C1083: Cannot open include file: 'capnp/common.h': No such file or directory
  *WARNING* no libcapnp detected or rebuild forced. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
  fetching https://capnproto.org/capnproto-c++-0.6.1.tar.gz into C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\bundled
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for pycapnp
  Running setup.py clean for pycapnp
Failed to build pycapnp
DEPRECATION: Could not build wheels for pycapnp which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pycapnp
    Running setup.py install for pycapnp ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\oliver\\AppData\\Local\\Temp\\pip-install-_0a_gt5x\\pycapnp_08ef60c046434841a72612502102f1f0\\setup.py'"'"'; __file__='"'"'C:\\Users\\oliver\\AppData\\Local\\Temp\\pip-install-_0a_gt5x\\pycapnp_08ef60c046434841a72612502102f1f0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\oliver\AppData\Local\Temp\pip-record-6s4cjy_z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\pycapnp'
         cwd: C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\
    Complete output (49 lines):
    Compiling capnp/lib\capnp.pyx because it changed.
    [1/1] Cythonizing capnp/lib\capnp.pyx
    C:\Users\oliver\AppData\Roaming\Python\Python38\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\capnp\lib\capnp.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\capnp
    copying capnp\version.py -> build\lib.win-amd64-3.8\capnp
    copying capnp\_gen.py -> build\lib.win-amd64-3.8\capnp
    copying capnp\__init__.py -> build\lib.win-amd64-3.8\capnp
    copying capnp\__init__.pxd -> build\lib.win-amd64-3.8\capnp
    copying capnp\c++.capnp -> build\lib.win-amd64-3.8\capnp
    copying capnp\schema.capnp -> build\lib.win-amd64-3.8\capnp
    creating build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\helpers.pxd -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\non_circular.pxd -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\__init__.pxd -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\asyncHelper.h -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\capabilityHelper.h -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\checkCompiler.h -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\fixMaybe.h -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\rpcHelper.h -> build\lib.win-amd64-3.8\capnp\helpers
    copying capnp\helpers\serialize.h -> build\lib.win-amd64-3.8\capnp\helpers
    creating build\lib.win-amd64-3.8\capnp\includes
    copying capnp\includes\capnp_cpp.pxd -> build\lib.win-amd64-3.8\capnp\includes
    copying capnp\includes\schema_cpp.pxd -> build\lib.win-amd64-3.8\capnp\includes
    copying capnp\includes\types.pxd -> build\lib.win-amd64-3.8\capnp\includes
    copying capnp\includes\__init__.pxd -> build\lib.win-amd64-3.8\capnp\includes
    creating build\lib.win-amd64-3.8\capnp\lib
    copying capnp\lib\capnp.pxd -> build\lib.win-amd64-3.8\capnp\lib
    copying capnp\lib\__init__.pxd -> build\lib.win-amd64-3.8\capnp\lib
    copying capnp\lib\pickle_helper.py -> build\lib.win-amd64-3.8\capnp\lib
    copying capnp\lib\__init__.py -> build\lib.win-amd64-3.8\capnp\lib
    copying capnp\lib\capnp.pyx -> build\lib.win-amd64-3.8\capnp\lib
    creating build\lib.win-amd64-3.8\capnp\templates
    copying capnp\templates\module.pyx -> build\lib.win-amd64-3.8\capnp\templates
    copying capnp\templates\setup.py.tmpl -> build\lib.win-amd64-3.8\capnp\templates
    running build_ext
    creating Users\oliver\AppData\Local\Temp\tmpogibf3w0
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /TpC:\Users\oliver\AppData\Local\Temp\tmpogibf3w0\vers.cpp /FoUsers\oliver\AppData\Local\Temp\tmpogibf3w0\vers.obj --std=c++11
    cl : Command line warning D9002 : ignoring unknown option '--std=c++11'
    vers.cpp
    C:\Users\oliver\AppData\Local\Temp\tmpogibf3w0\vers.cpp(4): fatal error C1083: Cannot open include file: 'capnp/common.h': No such file or directory
    *WARNING* no libcapnp detected or rebuild forced. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
    already have C:\Users\oliver\AppData\Local\Temp\pip-install-_0a_gt5x\pycapnp_08ef60c046434841a72612502102f1f0\bundled\capnproto-c++
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\oliver\\AppData\\Local\\Temp\\pip-install-_0a_gt5x\\pycapnp_08ef60c046434841a72612502102f1f0\\setup.py'"'"'; __file__='"'"'C:\\Users\\oliver\\AppData\\Local\\Temp\\pip-install-_0a_gt5x\\pycapnp_08ef60c046434841a72612502102f1f0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\oliver\AppData\Local\Temp\pip-record-6s4cjy_z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\pycapnp' Check the logs for full command output.
```

I tried building under WSL instead, but it only seems to build the capnp-cython:

```
oliver@Spud:/mnt/d/Dev/github.com/kfsone/pycapnp$ pip3 install --prefer-binary --upgrade --force --user pycapnp
Collecting pycapnp
  Downloading pycapnp-0.6.4.tar.gz (531 kB)
     |████████████████████████████████| 531 kB 1.9 MB/s
Building wheels for collected packages: pycapnp
  Building wheel for pycapnp (setup.py) ... done
  Created wheel for pycapnp: filename=pycapnp-0.6.4-cp38-cp38-linux_x86_64.whl size=4477318 sha256=f86d746d078019c59ed042885d19691c34078f9666d7ea49584814047b5aeca0
  Stored in directory: /home/oliver/.cache/pip/wheels/3b/df/d9/fcdb08d99e03da042d8d6cc55d127dbdbe4dc5d7597fcc13e9
Successfully built pycapnp
Installing collected packages: pycapnp
Successfully installed pycapnp-0.6.4
oliver@Spud:/mnt/d/Dev/github.com/kfsone/pycapnp$ find ~ -name "*capnp*"
/home/oliver/.cache/pip/wheels/3b/df/d9/fcdb08d99e03da042d8d6cc55d127dbdbe4dc5d7597fcc13e9/pycapnp-0.6.4-cp38-cp38-linux_x86_64.whl
/home/oliver/.local/lib/python3.8/site-packages/capnp
/home/oliver/.local/lib/python3.8/site-packages/capnp/includes/capnp_cpp.pxd
/home/oliver/.local/lib/python3.8/site-packages/capnp/lib/capnp.pyx
/home/oliver/.local/lib/python3.8/site-packages/capnp/lib/capnp.cpython-38-x86_64-linux-gnu.so
/home/oliver/.local/lib/python3.8/site-packages/capnp/lib/capnp.pxd
/home/oliver/.local/lib/python3.8/site-packages/capnp/c++.capnp
/home/oliver/.local/lib/python3.8/site-packages/capnp/schema.capnp
/home/oliver/.local/lib/python3.8/site-packages/pygments/lexers/__pycache__/capnproto.cpython-38.pyc
/home/oliver/.local/lib/python3.8/site-packages/pygments/lexers/capnproto.py
/home/oliver/.local/lib/python3.8/site-packages/pycapnp-0.6.4.dist-info
/home/oliver/.local/bin/capnpc-cython
/home/oliver/venv37/lib/python3.7/site-packages/pygments/lexers/__pycache__/capnproto.cpython-37.pyc
/home/oliver/venv37/lib/python3.7/site-packages/pygments/lexers/capnproto.py
```

which does not work:

```
oliver@Spud:/mnt/c/Users/oliver/go/src/github.com/kfsone/gomenacing/api/gomschema$ capnp compile gomschema.capnp -ocython
Traceback (most recent call last):
  File "/home/oliver/.local/bin/capnpc-cython", line 5, in <module>
    from capnp._gen import main
  File "/home/oliver/.local/lib/python3.8/site-packages/capnp/_gen.py", line 4, in <module>
    import schema_capnp
ModuleNotFoundError: No module named 'schema_capnp'
cython: plugin failed: exit code 1
```

**Comment by haata** [comment]
I don't believe v0.6.4 and earlier ever supported Win32.

I've added support starting from v1.0.0b1 (still working on putting out a proper v1.0.0 non-beta release).

**Comment by haata** [comment]
Please use https://pypi.org/project/pycapnp/1.0.0/ it should be the default now.
