### ISSUE TITLE
capnp.cpython-38-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by sohamm17** [capnproto/pycapnp#233]
I have downloaded and built capnproto from [here](https://github.com/capnproto/capnproto/releases/tag/v0.6.1). I installed it.
Machine: Intel x86_64
OS: Linux (Ubuntu 16.04)

I then installed pycapnp 0.6.1 for python 3.8. I am getting the following error:
```
Python 3.8.2 (default, Oct  4 2020
, 18:56:38) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import capnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/soham/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/__init__.py", line 34, in <module>
    from .version import version as __version__
  File "/home/soham/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/version.py", line 4, in <module>
    from .lib.capnp import _CAPNP_VERSION_MAJOR as LIBCAPNP_VERSION_MAJOR
ImportError: /home/soham/.pyenv/versions/3.8.2/lib/python3.8/site-packages/capnp/lib/capnp.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2kj9TimerImpl6atTimeENS_8AbsoluteINS_8QuantityIlNS_1_15NanosecondLabelEEENS3_9TimeLabelEEE
```

**Comment by haata** [comment]
I would recommend using 1.0.0b2. I'm not sure 0.6.1 will work with Python 3.8.
I'll be preparing an official 1.0.0 soon (tests are passing now).
