### ISSUE TITLE
pip install fails on alpine / non-wheel install missing dependencies

### ISSUE THREAD

**Issue by lindycoder** [capnproto/pycapnp#240]
Hello!

When trying to install on alpine, pkgconfig and cython seems to be missing.   (If i pre install pkgconfig, the cython import will cause the problem)

I'm expecting installing this will require compilation, yes, but right now it's not even reaching the compilation trying to install.
```
} ~$ docker run -it --rm python:3.8-alpine sh
/ # pip --version
pip 20.3.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
/ # pip install pycapnp
Collecting pycapnp
  Downloading pycapnp-1.0.0.tar.gz (528 kB)
     |████████████████████████████████| 528 kB 300 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qs8oinqa/pycapnp_3d05cfa5be814d5f9f7b70bd63a965b9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qs8oinqa/pycapnp_3d05cfa5be814d5f9f7b70bd63a965b9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-09_8y1nx
         cwd: /tmp/pip-install-qs8oinqa/pycapnp_3d05cfa5be814d5f9f7b70bd63a965b9/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qs8oinqa/pycapnp_3d05cfa5be814d5f9f7b70bd63a965b9/setup.py", line 12, in <module>
        import pkgconfig
    ModuleNotFoundError: No module named 'pkgconfig'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seem the pyproject.toml is not taken into consideration.

Thank you!

**Comment by adeebshihadeh** [comment]
Seems like this should be fixed by 1075ce005c2afe3125fd9364fa412782c29e7d2e. This seems worthy of updating the current release or doing a minor release.
