### ISSUE TITLE
Message is too large.  To increase the limit on the receiving end, see capnp::ReaderOptions.

### ISSUE THREAD

**Issue by RolandSall** [capnproto/pycapnp#269]
I am using capnp to read a bin file, below is the simple code that I am trying to run:

```
import capnp

addressbook_capnp = capnp.load({ADDRESS_TO_CAPNP_FILE})

f = open({FILE_TO_READ_DIRECTORY}, 'rb')
addresses = addressbook_capnp.Address.read_packed(f)
```

Once I run the following code this error is generated:

```
Traceback (most recent call last):
 File "proto.py", line 6, in <module>
 addresses = addressbook_capnp.Address.read(f)
File "capnp/lib/capnp.pyx", line 3227, in capnp.lib.capnp._StructModule.read
File "capnp/lib/capnp.pyx", line 3790, in capnp.lib.capnp._StreamFdMessageReader.__init__
capnp.lib.capnp.KjException: capnp/serialize.c++:177: failed: expected segmentCount < 512; Message has too many segments.
stack: 7fadad9aaaf2 551390 7fadad92f1d4 5a9d2b 50a532 50bf43 507cd3 50ae12 635261 635316 638ace 639670 4b0e3f 7fadaee1cbf6 5b2f09

```

If I Change the following line:

`addresses = addressbook_capnp.Address.read_packed(f)`

to:

`addresses = addressbook_capnp.Address.read(f)`

I will get the following error:

```
File "proto.py", line 6, in <module>
addresses = addressbook_capnp.Address.read(f)
File "capnp/lib/capnp.pyx", line 3227, in capnp.lib.capnp._StructModule.read
File "capnp/lib/capnp.pyx", line 3790, in capnp.lib.capnp._StreamFdMessageReader.__init__
capnp.lib.capnp.KjException: capnp/serialize.c++:177: failed: expected segmentCount < 512; Message has too many segments.
stack: 7f9cd4c1daf2 551390 7f9cd4ba21d4 5a9d2b 50a532 50bf43 507cd3 50ae12 635261 635316 638ace 639670 4b0e3f 7f9cd608fbf6 5b2f09
```

Any idea what might the solution be?

**Comment by nghiaho12** [comment]
Bump up traversal_limit_in_words as needed

`addresses = addressbook_capnp.Address.read_packed(f, traversal_limit_in_words=1024*1024*1024)`
