### ISSUE TITLE
Building issues `pycapnp v1.3.0` vs `capnproto v0.10.3`

### ISSUE THREAD

**Issue by sfavazza** [capnproto/pycapnp#340]
Hello there,

I am evaluating `pycapnp` in a docker container but I cannot successfully build the generated code for the `calculator` example.

Steps to reproduce:
- build a test image with the following Dockerfile:
```
FROM python:3.8
ARG USER=cooluser
ARG HOME=/home/${USER}
RUN useradd -ms /bin/bash ${USER}


# requirements for cap'n proto
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    libtool \
    pkg-config \
    cmake

# install "cap'n proto" from source (on master specific commit)
ARG TRGT_TAG="v0.10.3"
ARG BUILD_DIR=/opt/capnproto
RUN git clone https://github.com/capnproto/capnproto.git ${BUILD_DIR} \
    && cd ${BUILD_DIR} \
    && git checkout ${TRGT_TAG} \
    && cd c++ \
    && autoreconf -i \
    && ./configure \
    && make -j6 \
    && make install

RUN mkdir /data && chown ${USER}:${USER} /data

USER ${USER}

ENV PATH=${HOME}/.local/bin:$PATH

RUN cd ${HOME} \
    && pip install virtualenv \
    && virtualenv .pyvenv \
    && pip install \
    jinja2 \
    'cython<3'

ENV PATH=${HOME}/.pyvenv/bin:$PATH

WORKDIR /data
ENTRYPOINT [ "bash" ]
``` 
- mkdir ~/pycapnp-build-test
- docker run --rm -ti -v  ~/pycapnp-build-test:/data 
- from within the docker shell:
```shell
git clone https://github.com/capnproto/pycapnp.git .
pip install .
cd examples
capnpc -oc++ calculator.capnp
capnpc -ocython calculator.capnp
python setup_capnp.py build_ext --inplace
``` 

I got the following error:
```
Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
Compiling calculator_capnp_cython.pyx because it changed.
[1/1] Cythonizing calculator_capnp_cython.pyx
/home/cooluser/.pyvenv/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /data/examples/calculator_capnp_cython.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
        def __set__(self, value):
            self._set_literal(value)
    cpdef _get_previousResult(self):
        return self.thisptr_child.getPreviousResult()
        
    cpdef _set_previousResult(self, interface_t value):
                                   ^
------------------------------------------------------------

calculator_capnp_cython.pyx:174:36: 'interface_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.thisptr_child = (<C_DynamicStruct_Builder>struct.thisptr).asCalculator_Expression_call()
    
    cpdef _get_function(self):
        return self.thisptr_child.getFunction()
        
    cpdef _set_function(self, interface_t value):
                             ^
------------------------------------------------------------

calculator_capnp_cython.pyx:324:30: 'interface_t' is not a type identifier
Traceback (most recent call last):
  File "setup_capnp.py", line 37, in <module>
    ext_modules=cythonize('*_capnp_cython.pyx', language="c++")
  File "/home/cooluser/.pyvenv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
    cythonize_one(*args)
  File "/home/cooluser/.pyvenv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: calculator_capnp_cython.pyx
``` 

I tried with the `cap'n proto` library version _v0.10.3_ because of the `v1.3.0 (2023-01-26)` changelog, though trying with more recent `cap'n proto` versions (namely _v1.0.0_ and _v1.0.1_) gives the same result.

Any idea where the `interface_t` type is defined?

**Comment by tobiasah** [comment]
Have you tried the latest beta release (2.0.0.b1)?

**Comment by LasseBlaauwbroek** [comment]
You are trying to use an incomplete attempt at implementing a capnp->cython compiler. This code was never completed and has never worked.
